### ISSUE TITLE
Allow link properties to be primary keys

### ISSUE THREAD

**Issue by mrackwitz** [realm/realm-swift#2246]
Currently we support the types `RLMPropertyTypeString` and `RLMPropertyTypeInt` for primary keys. It could make sense to support links (`RLMPropertyTypeObject`) as well. tbd.
/c @i-schuetz @tgoyne

**Comment by jpsim** [comment]
The appropriate solution here I think would be to have a to-one relationship on the object that would be treated as a primary key value.

So instead of your proposal, you could do this:

```swift
class Person: Object {}

class PersonIdentifier: Object {
  dynamic var person = Person()
}

let personID = PersonIdentifier...
personID.person
```

This is analogous to a primary key lookup (e.g. given a personID, give me a single associated person).

**Comment by i-schuetz** [comment]
Just for context, this is the situation that lead to this issue:

```swift
class InventoryItem: Object {
    dynamic var quantity: Int = 0
    dynamic var product: Product = Product()
    dynamic var inventory: Inventory = Inventory()
}
```
Where I would like to create a unique on the product uuid and inventory uuid.

**Comment by jpsim** [comment]
> Where I would like to create a unique on the product uuid and inventory uuid.

Do you mean you want the combination of `product->uuid` and `inventory->uuid` to be unique? That would imply compound keys (#1192) something that we've considered before, but ultimately decided against.

If you mean "for a given `Product`, give me a unique `InventoryItem`", then my suggestion should work for you:

```swift
class Product: Object {
  dynamic var inventoryItem = InventoryItem()
  dynamic var uuid = 0
}
class Inventory: Object {}
class InventoryItem: Object {
  dynamic var quantity = 0
  dynamic var inventory = Inventory()
}
```

so that given a single `Product`, you can get `product.inventoryItem` rather than (what I assume) your requested API `InventoryItem(primaryKey: product)`.

**Comment by i-schuetz** [comment]
I mean a compound key... the inventory items are uniquely identified by a product and the inventory in which they are.
