### ISSUE TITLE
Enhanced IncorrectThreadException

### ISSUE THREAD

**Issue by pieterclaerhout** [realm/realm-swift#3350]
## Goals

Sometimes, we get reports in a production app about the fact that Realm objects are accessed from an incorrect thread. Troubleshooting those could be a little easier if we get some more information in the exception.
## Expected Results

Instead of just getting the plain exception, we would like to get the following result:

```
Realm object of type <classname> accessed from incorrect thread <thread_name>.
```

This would give you at least a clue on where to start looking.

The problem in Objective-C is that when you get this error in a block, it's very hard to find the correct stack trace that leads you to the source of the problem.
## Version of Realm and Tooling

We are using the Objective-C version (0.98.5) of the Realm SDK on iOS. We are using CocoaPods as the dependency manager.

**Comment by jpsim** [comment]
I'm sure there are improvements we can do in this area. Thanks for the suggestion!

**Comment by JadenGeller** [comment]
It isn't possible to specify the object type since the incorrect thread exception is thrown at the beginning of the transaction, before any writes occur. I can improve the error to specify thread name/id and reason for failure (begin transaction, refresh, etc.), but indicating the object type that *would have* been written to would be difficult. Can't all this information be determined from the exception alone as long as exception breakpoints are enabled anyway?
