### ISSUE TITLE
Add Catalyst installation example

### ISSUE THREAD

**Issue by tgoyne** [realm/realm-swift#6261]
Depends on https://github.com/realm/realm-cocoa/issues/6259.

**Comment by obuseme** [comment]
Is there any summary of how to install RealmSwift for catalyst short of this issue being completed?

**Comment by jhoughjr** [comment]
does this mean catalyst is not supported for realm-swift?
the realm react native appears to since mid 2020.
I enabled catalyst and ran my working app on the Mac to an immediate crash in realm:
2022-04-19 15:27:13.838957-0500 ctx[31206:7589368] *** Terminating app due to uncaught exception 'RLMException', reason: 'Keychain returned unexpected status code: -34018'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001809eeb08 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x0000000180739e14 objc_exception_throw + 60
	2   ctx                                 0x000000010494021c _ZL17RLMTranslateErrorIZ49-[RLMApp initWithId:configuration:rootDirectory:]E3$_0EDaOT_ + 128
	3   ctx                                 0x0000000104940034 -[RLMApp initWithId:configuration:rootDirectory:] + 436
	4   ctx                                 0x0000000104940550 +[RLMApp appWithId:configuration:rootDirectory:] + 296
	5   ctx                                 0x00000001049406ac +[RLMApp appWithId:configuration:] + 96
	6   ctx                                 0x000000010494076c +[RLMApp appWithId:] + 72
	7   ctx                                 0x0000000104847094 $sSo6RLMAppC2idABSS_tcfCTO + 56
	8   ctx                                 0x00000001048f432c $s3ctx0A3AppVACycfC + 148
	9   ctx                                 0x00000001048f4558 $s3ctx0A3AppV7SwiftUI0B0AadEPxycfCTW + 12
	10  SwiftUI                             0x00000001bda09550 $s7SwiftUI3AppPAAE4mainyyFZ + 112
	11  ctx                                 0x00000001048f4224 $s3ctx0A3AppV5$mainyyFZ + 40
	12  ctx                                 0x00000001048f456c main + 12
	13  dyld                                0x0000000108a19088 start + 516
)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'RLMException', reason: 'Keychain returned unexpected status code: -34018'
terminating with uncaught exception of type NSException

**Comment by tgoyne** [comment]
Incidentally did this as part of adding visionOS support in #8309.
