### ISSUE TITLE
Using Multiple @ObervedResult with different realm configurations

### ISSUE THREAD

**Issue by pridees** [realm/realm-swift#7150]
Hi guys! 

It's good idea is hiding whole crud logic under the hood of property wrappers. 👏

I have faced with issue where I what to use couple of entities which have different realms in single View and I got the app termination because EnvironmentValue is providing an only one realm configuration.

https://github.com/realm/realm-cocoa/blob/f0af9a11038c44d0de3aac11ba6b7e27d7432660/RealmSwift/SwiftUI.swift#L266

I saw in the code example above this constructor: 

```swift
@ObservedObject(UserData.self, configuration: ....) 
```

Why it doesn't work? It's so really handy - providing particular configuration as I want.

At the time I have: 

```swift
@ObservedResults(Account.self) var accounts // use .environment(\.realmConfiguration) implicitly and working properly
@ObservedResults(
     UserPublicData.self, 
     configuration: RealmApp.createConfiguration(user: RealmApp.default.realmUser!, partition: "shared")
) var userPublicData // doesn't work
```

and it is dropping with:

```
*** Terminating app due to uncaught exception 'RLMException', 
reason: 'Object type 'UserPublicData' is not managed by the Realm. 
If using a custom `objectClasses` / `objectTypes` array in your configuration, add `UserPublicData` to the list of `objectClasses` / `objectTypes`.'
```

static method of RealmApp:
```swift
static func createConfiguration(user:RealmSwift.User, partition: String) -> Realm.Configuration {
    var configuration = user.configuration(partitionValue: partition)
    let partitionKey = String(partition.split(separator: "=")[0])

    if partitionKey == "account" {
        configuration.objectTypes = accountObjectTypes
    } else if partitionKey == "shared" {
	configuration.objectTypes = [UserPublicData.self]
    }
    return configuration
}
```

PS:
Guys, please do something with realm configurations. I what to provide bunch of partition values to retrieve shared entities from any partitions as if it's just one. 🙏

**Comment by jsflax** [comment]
Hmm, thanks for bringing this up.

In its current state, `@ObservedResults` can only handle one configuration per View. Mixing and matching within the same view isn't currently supported– it will default to the Environment configuration.

I can file a PR to enable this behaviour as this use case could _probably_ be considered broken.

In the meantime, having separate Views for your Results is the simple workaround here.

**Comment by Kotovskyart** [comment]
Thank you @jsflax for fast answer! 

In my case I should get some data from  different realms to calculate them and set to view. E.g. I have some transactions which different people made in thier own partitions. And then they want to share this transactions between each other (I append new partition to canRead/canWrite list) and review in single list as if it’s own transactions with common filtering and sorting, and see resulting payment amount of all transactions. 

For now, it will be good solution, if I can provide needed configuration to property wrapper directly or use from environment by default. 

Please, think about how to hide under the hood work with some configurations for one Entity, in order to retrieve data from different realms to one view. Sometimes I can’t assume how much partitions I should sync and iterate. It seems needed some solution for that.

Thank you so much!

**Comment by rromanchuk** [comment]
In the context of someone using both SwiftUI with UIKit,  would it be possible to take an existing `Results<Object>` and assign to the view instead of defining in the view. I guess thats just a swift language feature i need to better understand.

https://github.com/realm/realm-cocoa/blob/v10.12.0/RealmSwift/SwiftUI.swift#L287

Or could i at least do something like this?

```swift
// Somewhere in UIKit world
let myObjects: ObservedResults<Object> = .init(Object.self, filter: NSPredicate(format: "mything.id == %@", id))
MyView(myObjects: myObjects)
```

```swift
struct MyView: View {
  @ObservedResults(Object.self) var myObjects
}
```

or i guess i should probably remove the @ wrapper definition and just use 
`var myObjects: ObservedResults<Object>`

I guess what i'm really trying to solve is how to set the filter that requires requires values from a UIKit parent,  since it seems i'm out of scope/outside initialization process. I've never used swiftui so a bit lost, just trying to get an existing realm collection as the data source.

**Comment by aehlke** [comment]
Oof, this is quite a surprise to run into late into architecting a data model

**Comment by aehlke** [comment]
Looks like this might resolve this issue: https://github.com/realm/realm-swift/pull/7487

**Comment by leemaguire** [comment]
@aehlke the PR you refer to did fix this issue.

**Comment by leemaguire** [comment]
Closed via https://github.com/realm/realm-swift/pull/7487
