### ISSUE TITLE
Static framework compiled for Swift 5.7

### ISSUE THREAD

**Issue by aheze** [realm/realm-swift#7861]
### Problem

After downloading `realm-swift-10.28.1.zip` from the [releases](https://github.com/realm/realm-swift/releases) tab and dragging it into Xcode, I get this error:

> Module compiled with Swift 5.6 cannot be imported by the Swift 5.7 compiler: /Users/aheze/Library/Developer/Xcode/DerivedData/MyApp-efamboqfriququavkcisfborlrqr/Index/Build/Products/Debug-iphoneos/RealmSwift.framework/Modules/RealmSwift.swiftmodule/arm64-apple-ios.swiftmodule

<img width="925" alt="Screenshot of the error" src="https://user-images.githubusercontent.com/49819455/175381801-03d723bd-89cc-446d-b514-7e322136071e.png">

I'm using Xcode 14.0 beta (14A5228q). Would it be possible to have a precompiled static framework for Swift 5.7/Xcode 14? It would make compiling the project much faster compared to when using Swift Package Manager.

### How important is this improvement for you?

I'd like to see it, but have a workaround

**Comment by dianaafanador3** [comment]
Hi @aheze because Xcode 14 is still in beta, we are not using it to build our static framework release. But you can do this by yourself.
Make sure you have selected your Xcode beta as your default first using
`sudo xcode-select -s <Path_xcode_beta>`
You can print your current default Xcode with
`xcode-select --print-path`

After this you can generate your own `xcframework`, running the following command
`sh build.sh xcframework ios`

**Comment by aheze** [comment]
Thanks! It worked.
