### ISSUE TITLE
Getting Realm accessed from incorrect thread. Error After Updating to Xcode 14 and iOS 16

### ISSUE THREAD

**Issue by idenizalan** [realm/realm-swift#7962]
### How frequently does the bug occur?

All the time

### Description

Normally, I wasn't getting this error before the update; however, after I updated I cannot get the objects from my realm sync database. This error occurs while I'm trying to get data with realm.objects method.

### Can you reproduce the bug?

Not yet

### Version

10.29.0

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

iOS16

### Build environment

Xcode version: 14
Dependency manager and version: 10.29.0

**Comment by dianaafanador3** [comment]
@idenizalan Can you show me the code where you get this error?, Like the error mentions you probably trying to access the realm in a different thread from the one it was created.

**Comment by labradon** [comment]
Experiencing the same error in XCode 14.0 (14A309) and iOS 16.0. Error can be provoked with code as simple as this
```swift
func fetchPets() async throws -> [Pet] {
    let realm = try Realm()
    let pets = try await realm.objects(Pet.self)  // Error is thrown here
    return pets
}

Task {
    let pets = try await fetchPets()
}
```

Was able to workaround this problem by adding `@MainActor` to the function definition. However, this negatively effects the UI performance and can not be a final solution.

**Comment by dianaafanador3** [comment]
@labradon firstable, we don't expose any async or throwable function to query an object, so instead of `let pets = try await realm.objects(Pet.self)` use `let pets = realm.objects(Pet.self)`
Also you should mark the async function as @MainActor
```
@MainActor func fetchPets() async throws -> [Pet] {
    let realm = try await Realm()
    let pets = realm.objects(Pet.self)  // Error is thrown here
    return pets
}
```
This will guarantee that all the access to the realm are done in the same thread.
From Swift 5.7 https://github.com/apple/swift-evolution/blob/main/proposals/0338-clarify-execution-non-actor-async.md there is no guarantee that async functions will run on the same thread, this most of the time happened to work with Xcode 13, but with the introduction of Xcode 14 and Swift 5.7 this is no longer the case. 
 
We are working on a better support for this, but on the meantime using the `@MainActor`  solves the issue.

**Comment by dianaafanador3** [comment]
@idenizalan if this is you case as well, please update your code to use @MainActor

**Comment by idenizalan** [comment]
Hello, when I added @MainActor to my async functions it worked exactly like before! Thank you very much both.

**Comment by labradon** [comment]
@dianaafanador3 Thanks a lot for the clarification. I didn't know about the the specific change regarding actors in Swift 5.7, this helps a lot. Again, I can confirm that using `@MainActor` solves the error.  

*Sorry for the misuse of `realm.objects`. I typed the comment up quickly before work and missed this part.*

**Comment by LilaQ** [comment]
Just saying "thanks", encountered the same situation when migrating to Xcode 14, and can confirm, this modification to the code helps.
