### ISSUE TITLE
Not working with  HandyJSON

### ISSUE THREAD

**Issue by locooo** [realm/realm-swift#8043]
### Problem

import Foundation
import RealmSwift
import HandyJSON

class HomeHandyJson: Object, HandyJSON {
        // @Persisted

    @Persisted var is_expire: String?

    @Persisted   var use_result_imgs: MyResullt?

    required  override init(){
        super.init()
    } 
}

class MyResullt: Object, HandyJSON {
    @Persisted var imgs: List<ImgsSSxxx>
    required override init(){
        super.init()
    } 
}

class ImgsSSxxx: Object, HandyJSON {
    @Persisted  var attachment_id: String?
    @Persisted  var fileName: String?
    @Persisted  var seal_id: String?
    @Persisted  var confirm_status: Int?
    @Persisted  var path: String?
    @Persisted   var path_thumbnail: String?
    @Persisted  var fileLength: Int?
    @Persisted var oss_url: String?
    @Persisted  var fileSize: String?
    required override init(){
        super.init()
    } 
}

                    let realm = try! Realm()
              
                    try! realm.write {
                      //can not add to realm  and  bb is nil 。when i remove  @Persisted and Object  it can be a HomeHandyJson
                        let bb = HomeHandyJson.deserialize(from: responseDic["data"] as! [String : Any])
   
                        realm.add(bb!)
                    }

**Comment by dianaafanador3** [comment]
@locooo we don't guarantee support with other libraries, probably this is happening because `HandyJSON` doesn't consider the use of property wrappers when declaring a property, which may be an issue when they are mapping (reflection in a property which use a wrapper reads the property name with a `_` at the beginning), and also casting to a property type (in this case `RealmSwift.Persisted`).
Our `@Persisted` works with Codable which can be used to deserialise data into an object, but if you want to stick to HandyJSON I recommend you use `@objc dynamic var` to declare your model.

**Comment by dianaafanador3** [comment]
Closing this as there is no issue in our side.
