### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by uuzd** [realm/realm-swift#8120]
### How frequently does the bug occur?

-- select --

### Description

https://data.mongodb-api.com/app/realmsdkmetrics-zmhtm/endpoint/metric_webhook/metric?data= 

### Can you reproduce the bug?

Always

### Version

v10.32.2

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 15.5

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by dianaafanador3** [comment]
@uuzd can you elaborate more how do you get this error?

**Comment by StefaniOSApps** [comment]
same issue
https://data.mongodb-api.com/app/realmsdkmetrics-zmhtm/endpoint/metric_webhook/metric?data

**Comment by StefaniOSApps** [comment]
Thank you for your post. I fully agree with you that Realm Swift's default tracking behaviour is somewhat unexpected and problematic, especially considering that Realm's primary purpose is to provide a local database.

Although it's possible to disable the analytics feature via the REALM_DISABLE_ANALYTICS environment variable, in my opinion, this is not an ideal solution. Firstly, this is not obvious or well-documented and requires additional research and understanding from developers. Secondly, this is not very convenient as it means developers need to pass additional arguments each time they use Realm in a CI environment.

I agree with you that having the ability to disable tracking in the "Realm.Configuration" would be a more sensible and user-friendly solution. This would give developers more control and transparency over the behaviour of their applications, and would make it easier for them to comply with their users' privacy regulations.

With respect to privacy and user control, this behaviour should be considered as disabled by default, or at least it should be easier to disable it. It would be interesting to hear the thoughts and opinions of other developers on this matter.

**Comment by StefaniOSApps** [comment]
> What issue is that?

I'm referring to the default behavior of the Realm Swift library for error reporting and tracking. Currently, these features are enabled by default, which can cause issues, particularly when an application is offline, or when for privacy reasons, no reporting or tracking is desired.

Although it's possible to disable these features with the `REALM_DISABLE_ANALYTICS` environment variable, this should not be the standard way to do it. This isn't necessarily intuitive and requires additional efforts in the CI pipeline.

Therefore, I suggest that these features should be disabled by default, or at least there should be a more obvious and user-friendly way to disable them. Such a way could be implemented in the "Realm.Configuration". This would make it easier for developers to respect their users' privacy rights and make the usage of their applications more transparent.

I would like to additionally point out that these features are not expected in a Realm database, which is primarily used for local data storage. Typically, one would assume that a local database does not forward or analyze user data. Therefore, it's even more important that developers can easily and obviously disable these features in order to comply with privacy requirements.

**Comment by tgoyne** [comment]
The analytics code is not compiled at all for device builds. It is only present in simulators, so unless you are doing something very unusual it will never have any implications for your users.
