### ISSUE TITLE
Could not find module 'RealmSwift' for target 'x86_64-apple-ios-simulator'

### ISSUE THREAD

**Issue by notoriouscode97** [realm/realm-swift#8172]
### How frequently does the bug occur?

Always

### Description

I've added the Realm library through SPM to the project and since then I've been experiencing this error.
I can compile but it stays there and is annoying.

### Can you reproduce the bug?

Always

### Reproduction Steps

Add import RealmSwift then
Just compile the project

### Version

10.37.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 16.1 simulator

### Build environment

Xcode version: 14.1
Dependency manager and version: SPM

**Comment by dianaafanador3** [comment]
Hi @notoriouscode97 It seems like you are building for every architecture during debug, do you `Debug Build Architecture Only` set to No in your build configurations?. 
If you can compile is because there is no error for the current compilation, please clean you build folder s you can clean the error.

**Comment by notoriouscode97** [comment]
`Debug Build Architecture Only` was set to `yes`, when I changed it to `No` then the warning disappeared

**Comment by dianaafanador3** [comment]
I see this an error instead of a warning, and it disappears when setting `Debug Build Architecture Only` to Yes (you shouldn't be building for all architectures when debugging, unless there is an specific use case you want to test) . Can you please attach a repo project where I can see this?

**Comment by notoriouscode97** [comment]
https://drive.google.com/file/d/1GGMOcyn1LoaAdFiCIiWSKNrtiL5Jkgv6/view?usp=sharing You can download a sample project here with this error

**Comment by dianaafanador3** [comment]
Any reason you are particularly excluding (i386 and arm64) architectures in Debug and Release?

**Comment by notoriouscode97** [comment]
In the project that I'm working on we are using some libraries like GooglePlaces that do not support SPM that's why we are using Cocoapods for them. When you try to run the project without excluding arm64 you will get an error 
`[Xcode building for iOS Simulator, but linking in an object file built for iOS, for architecture 'arm64'](https://stackoverflow.com/questions/63607158/xcode-building-for-ios-simulator-but-linking-in-an-object-file-built-for-ios-f)`

**Comment by dianaafanador3** [comment]
When you are building for the iPhone simulator, you are actually building for "arm64" architecture, so the issue is not our SDK which is prepared to be build for "arm64", but GooglePlaces is not updated for newer architectures in Cocoapods. The best solution is to use the xcframework https://developers.google.com/maps/documentation/places/ios-sdk/config#xcframework-manual from them and not use Cocoapods to install GooglePlaces.

**Comment by GaneshRajuGalla** [comment]
@dianaafanador3 i am also facing same issue 

Could not find module 'RealmSwift' for target 'x86_64-apple-ios-simulator'; found: arm64-apple-ios-simulator, at: /Users/ganesh/Library/Developer/Xcode/DerivedData/appname/Build/Products/Debug-iphonesimulator/RealmSwift/RealmSwift.framework/Modules/RealmSwift.swiftmodule

Xcode 14.2

**Comment by dianaafanador3** [comment]
@GaneshRajuGalla did you read the comments above, probably you have something similar in your project build setting which may be causing this error to pop.
