### ISSUE TITLE
Repeat from Step 1 to 3, it doesn't reach 4, and crashes with exception 

### ISSUE THREAD

**Issue by yalamandarao** [realm/realm-swift#8325]
### How frequently does the bug occur?

Yes

### Description

```
 func testdeletSubDBChecklistQuestions(checklistQuestionId: String, inspectionCaseNumberKey: String){
        let deleteData = realm.objects(DBChecklistQuestion.self).filter("checklistQuestionId == %@ && inspectionCaseNumberKey == %@", checklistQuestionId, inspectionCaseNumberKey)
        if(!deleteData.isEmpty) {
            print("Deleted the sub question")
            DispatchQueue.main.async {
                try? self.realm.write {
                    self.realm.delete(Array(deleteData))
                }
            }
        }
    }

```
Error Message : Terminating app due to uncaught exception 'RLMException', reason: 'List is no longer valid. Either the parent object was deleted or the containing Realm has been invalidated or closed.'

### Can you reproduce the bug?

Always

### Version

10.40.2

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS

### Build environment

Xcode version: ...
Dependency manager and version: ...
Realm : 10.40.2
RealmDatabase : 13.15.0

**Comment by bdkjones** [comment]
I'm not with Mongo, but it seems like this might be user error. You're dispatching to the main queue, but using the same `realm` that you used just a few lines above. That's 100% gonna ruin your life: Realms are thread-limited. 

Unless your entire function is *also* running on the main queue (in which case you're just needlessly dispatching async), the problem lies in you using Realms across threads.

**Comment by dianaafanador3** [comment]
I'll recommend to open the realm in the thread you are gonna perform your operation like mentioned above. If you want the UI to be updated on the main thread you should be updating the binding on the UI on the main thread, not the database operations.
Also, if you don't need to convert a collection into an Array to use the `delete(collection)` function. You should be able to do this.
```
let deleteData = realm.objects(DBChecklistQuestion.self).where { $0.checklistQuestionId == checklistQuestionId && $0.inspectionCaseNumberKey == inspectionCaseNumberKey }
try realm.write {
   realm.delete(deleteData)
}
```
You get the error because you are trying to do an operation with a List which is already invalidated or removed, probably you are not updating your references after you are deleting some objects. To about thus update your references after delete or check if the list is invalidated before use.
`if !list.isInvalidated() { }`
