### ISSUE TITLE
realm-swift-10.42.0 was built using Swift 5.9.0.120.7 (Xcode 15 beta 4).

### ISSUE THREAD

**Issue by datinc** [realm/realm-swift#8327]
### How frequently does the bug occur?

Always

### Description

The release notes for v10.42.0 state that Xcode 15 beta 5 is supported. Xcode beta 5 uses Swift 5.9.0.124.4. realm-swift-10.42.0 is compiled with 5.9.0.120.7.

### Stacktrace & log output

```shell
/**/Array+realm.swift:10:8: Compiled module was created by a different version of the compiler '5.9.0.120.7'; rebuild 'RealmSwift' and try again: /**/Build/Products/Debug-iphonesimulator/RealmSwift.framework/Modules/RealmSwift.swiftmodule/x86_64-apple-ios-simulator.swiftmodule
```

### Can you reproduce the bug?

Always

### Reproduction Steps

* Download Xcode beta 5
* Update realm to 10.42.0
* Build and run the project using Xcode beta 5

Expectation:
* project compiles

Actual Result:
* Build fails with error to recompile RealmSwift

### Version

10.42.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 17

### Build environment

Xcode version: Xcode 15 beta 5

**Comment by dianaafanador3** [comment]
Hi @datinc even though we support RealmSwift with the latest Xcode version Xcode 15 beta 5, we don't release our packages using beta versions, that's why we distribute for our supporter version (14.1, 14.2 and 14.3.1), if you want to generate a version which you can use with Xcode 15 beta you need to do it locally running `sh build.sh build`
