### ISSUE TITLE
Realm XCFramework Not Compatible with SPM in Recent Releases

### ISSUE THREAD

**Issue by alibaqbani** [realm/realm-swift#8361]
### Problem

The latest version of the Realm XCFramework is not compatible with the Swift Package Manager (SPM) as a binary target. The provided asset does not have an XCFramework bundle in its root directory.

The version of the Realm XCFramework that is compatible with SPM is v10.42.0. You can find the assets for this version at the following link: <https://github.com/realm/realm-swift/releases/tag/v10.42.0>

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by tgoyne** [comment]
Looks like the build script is using an absolute path for the files in the Realm zip, which is very not correct, but the RealmSwift ones are valid. I've manually swapped out the Realm zip for the 10.42.2 release with a valid one.

**Comment by alibaqbani** [comment]
We can keep this issue open until the script output path gets fixed.

**Comment by bdkjones** [comment]
Just a heads-up for others who might google: this is a MUCH bigger deal than it seems from the notes here, because Xcode 15 (the final release build) crashes with 100% reproducibility if you try to use the "Direct Distribution" option to export a Notarized Mac App that depends on RealmSwift 10.42.2:

<img width="779" alt="Screenshot 2023-09-18 at 21 32 31" src="https://github.com/realm/realm-swift/assets/926566/c3ba26fc-1b2b-4016-a209-b628a4c2354f">

Earlier builds of Xcode 15 did not exhibit this problem with 10.42.2.

10.42.1 works fine and 10.42.3 work fine. It took me a long time to figure out the cause because the crash happens on an assertion about a plist file not being locked correctly. Updating Realm resolved the issue. No other changes were made.
