### ISSUE TITLE
Add Privacy Manifest

### ISSUE THREAD

**Issue by chrs1885** [realm/realm-swift#8428]
### Problem

We recently became aware that, according to the new Apple privacy regulations, third-party SDKs will also be required to provide a [Privacy Manifest ](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files) to ensure compliance with privacy policies in the future.

### Solution

Add a Privacy Manifest

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

-- select --

**Comment by nokiaowner** [comment]
Hello,

This is extremely important for us too. I appreciate that enforcement won't happen until Spring 2024 but I wanted to make contact so that we can plan our own app releases to take this into account.

In addition to the OP question here's a list of useful references:

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_data_use_in_privacy_manifests

https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

https://developer.apple.com/videos/play/wwdc2023/10060/

Thanks

**Comment by FONickReichard** [comment]
+1

**Comment by wlxo0401** [comment]
+1

**Comment by wlxo0401** [comment]
+1

**Comment by wlxo0401** [comment]
+1

**Comment by nokiaowner** [comment]
Hello,

Is there a tentative date and target release version for privacy manifest to be included in the SDK?

Thanks

**Comment by giobass** [comment]
+1

**Comment by kishorepran** [comment]
+1
