### ISSUE TITLE
Memory overflow in Swift, exceeding the size limit of 12MB.

### ISSUE THREAD

**Issue by sanjinhub** [realm/realm-swift#8472]
### How frequently does the bug occur?

Always

### Description

```swift
func getData() -> Results<Phone> {
    let items = sharedRealmDB(dbFile: "db.realm").objects(Phone.self).sorted(by: \.phone, ascending: true)
    return items
}
``` 

```swift
private func addOrRemoveIncrementalBlockingPhoneNumbers(to context: CXCallDirectoryExtensionContext) {
    // Retrieve any changes to the set of phone numbers to block from data store. For optimal performance and memory usage when there are many phone numbers,
    // consider only loading a subset of numbers at a given time and using autorelease pool(s) to release objects allocated during each batch of numbers which are loaded.

    let phoneData = getData() 
    print(phoneData)
}
``` 
I am using the CallKit -> CallDirectoryHandler to read data.

<img width="1401" alt="image" src="https://github.com/realm/realm-swift/assets/53846155/402f1fe1-a060-441c-9a5f-2650b72f438c">

<img width="1708" alt="image" src="https://github.com/realm/realm-swift/assets/53846155/e050c069-85f9-42f7-955c-d8af0d5101ea">

How to solve it? Is there a feature of offset and limit?

### Can you reproduce the bug?

Always

### Reproduction Steps

CallKit -> CallDirectoryHandler can be called to reproduce.

### Version

v10.46.0

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS

### Build environment

Xcode version: ...
Dependency manager and version: ...

**Comment by nirinchev** [comment]
You say this reproduces consistently for you - does it happen on the simulator or a physical device? Also, do you have a simple project you can upload that we can use to reproduce it locally?

**Comment by Jaycyn** [comment]
The report here is a bit unclear.

The first screenshots of code reads in the Realm objects in a lazy-loading fashion; e.g. there could be 50,000 objects and that really impact memory. However, that code isn't used anywhere else.

The screenshot with the `BaseDescriptor` object in it doesn't appear to be related to Realm, and then the calling code calls a function `getPhoneRulesData` which appears to be unrelated the rest of the code.

Can you edit and focus the question on the issues with Realm and include a duplicatable example? If the issue is with `CallKit` this would not be correct forum.
