### ISSUE TITLE
Realm-swift is utilising 100-150% CPU when in background

### ISSUE THREAD

**Issue by sportyravi** [realm/realm-swift#8497]
Realm-swift is utilising 100-150% CPU when in background. Our app is having Realm 10.44.0 packaged into the code and we have observed a drastic decrease in performance when app was put into background. I will not be in a position to share screenshots of the code but we observed this behaviour all the time. Request to optimise this performance issue in future releases. App performs CRUD operations when in background.

XCode 15.2
Deployment Target : iPhone 
Tested in: iPhone 12 Pro Max, iPhone 13 Pro Max, iPhone 14

**Comment by nirinchev** [comment]
Are you using Sync or is this happening with just the local database. There's nothing obvious that would explain a drop in performance other than just the kernel allocating fewer resources to your app.

If you're able to consistently reproduce the issue, it would help to extract a minimal repro case in a new project and share that with us so that we can profile and address the issues.
