### ISSUE TITLE
`RLMException` in unit tests

### ISSUE THREAD

**Issue by skywalkerdude** [realm/realm-swift#8533]
### How frequently does the bug occur?

Always

### Description

I am unable to use realm in unit tests that also utilize Quick async tests: https://github.com/Quick/Quick/issues/1218.

I reported a bug to them, and they said it was a bug with how Realm handles concurrency: https://github.com/Quick/Quick/issues/1218#issuecomment-1884185159.

### Can you reproduce the bug?

Always

### Reproduction Steps

1. Create new project.
2. Install RealmSwift, Nimble,  and Quick.
3. Use sample code to reproduce:

```
import RealmSwift
import Quick
import Nimble
import XCTest
import Combine

// swiftlint:disable all
final class SampleSpec: AsyncSpec {
    override class func spec() {
        var realm: Realm!

        var thing: Obj!

        var failure: XCTestExpectation!
        var finished: XCTestExpectation!
        var value: XCTestExpectation!
        var cancellable: AnyCancellable?

        beforeEach {
            Realm.Configuration.defaultConfiguration.inMemoryIdentifier = current.name
            realm = try! Realm()

            thing = Obj()

            try! realm.write {
                realm.add(thing)
            }

            failure = current.expectation(description: "Invalid.failure")
            failure.isInverted = true
            finished = current.expectation(description: "Invalid.failure")
            value = current.expectation(description: "Invalid.failure")
        }

        afterEach {
            await MainActor.run {
                current.waitForExpectations(timeout: 10)
            }
            cancellable?.cancel()
        }

        it("works?") {
            cancellable = realm.objects(Obj.self)
                .collectionPublisher
                .sink(receiveCompletion: { completion -> Void in
                    switch completion {
                    case .failure:
                        failure.fulfill()
                    case .finished:
                        finished.fulfill()
                    }
                    return
                }, receiveValue: { isFavorite in
                    value.fulfill()
                })
        }
    }
}

class Obj: Object {
    @Persisted var name: String = ""
}
```

### Version

10.49.1

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS 17.2

### Build environment

Xcode version: Version 15.2 (15C500b)
Dependency manager and version: 
  - Realm (10.49.1):
    - Realm/Headers (= 10.49.1)
  - Realm/Headers (10.49.1)
  - RealmSwift (10.49.1):
    - Realm (= 10.49.1)
  - Quick (7.5.0)
  - Nimble (13.2.1):
    - CwlPreconditionTesting (~> 2.2.0)

**Comment by tgoyne** [comment]
Realm's notifications require a scheduler to post the notifications on. By default we use the current thread's runloop (mostly since historically that's the only thing we *could* use), which these days only works on the main thread unless you've specifically gone out of your way to set up a runloop on the background thread.

The simplest way to fix your test is to add a `.subscribe(on:)` call to your Combine pipeline, passing in a serial dispatch queue. This will result in your `.sink()` block being called on that queue, so if you do anything more complicated there than call `fulfill()` thread-safety can get complicated. Notably you can't access the `realm` instance from within that block and instead have to use the values passed to it as a parameter.

A more complicated approach would be to confine your entire test to an instance of an actor and do `realm = try! await Realm(actor: actor)`, but I have no idea if Quick has reasonable support for doing that.
