### ISSUE TITLE
Apple Privacy Manifest - Realm 10.49.2 - ISSUE: NSPrivacyAccessedAPICategoryDiskSpace

### ISSUE THREAD

**Issue by salvatoreboemia** [realm/realm-swift#8555]
### How frequently does the bug occur?

Always

### Description

Hi,

we still receiving emails from Apple about the Privacy Manifest

<img width="1048" alt="Screenshot 2024-04-22 at 10 20 08" src="https://github.com/realm/realm-swift/assets/20614870/7e9deb83-6a40-417e-9498-fe29c5179594">

Realm: 10.49.2 

The privacy manifest is still empty

<img width="370" alt="Screenshot 2024-04-22 at 10 17 07" src="https://github.com/realm/realm-swift/assets/20614870/3868371a-95b6-45c8-90c8-273240348e82">

and now we have also this issue in the packages with this warning

<img width="339" alt="Screenshot 2024-04-22 at 10 23 40" src="https://github.com/realm/realm-swift/assets/20614870/e36c3f95-bc63-45cc-866f-930d08ecdb6e">

Do you have some news about these issues?

Thanks

### Can you reproduce the bug?

Always

### Version

10.49.2

### What Atlas Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

iOS all version

### Build environment

Xcode version: 15.3

**Comment by tgoyne** [comment]
When I build an app using Realm Swift v10.49.2 using SPM I get the following files in the app directory:
![image](https://github.com/realm/realm-swift/assets/408944/78c6d704-8f8b-44be-af14-dc989e2b12b8)

Each of the bundles contains the expected PrivacyInfo.xcprivacy with the expected contents. I've submitted this app to the app store (with it currently in the Ready for Review step) and also TestFlight and after several hours I have not received any emails.

**Comment by salvatoreboemia** [comment]
News on this issue? 

I added in my own privacy manifest your disk api reason. And just after adding it I am not receiving emails from Apple. the realm swift folder always has an empty manifest. and also problems with the. erodo and realm database. as per the attached screens

**Comment by knowledgeisporridge** [comment]
I'm not the original poster, but I can echo the issue.

@nirinchev 

1. Yes, the PrivacyInfo.xcprivacy in the RealmSwift bundle of the built app [matches the one linked](https://github.com/realm/realm-swift/blob/master/RealmSwift/PrivacyInfo.xcprivacy) (i.e. essentially empty)
2. Yes, the PrivacyInfo.xcprivacy in the RealmDatabase bundle of the build app matches [the one you linked](https://github.com/realm/realm-core/blob/master/src/spm/PrivacyInfo.xcprivacy) 
3. The "Upload issues" email is delivered when the binary is sent for review (AppStore or Beta Review).

Built with Xcode 15.3

**Comment by tgoyne** [comment]
I think inheriting privacy manifests from SPM packages just plain doesn't work when the package is built as a static library and once again two teams at Apple have failed to talk to each other. AFAICT the app store scans bundles contained in dynamic frameworks for privacy manifests, but only checks the top-level PrivacyInfo.xcprivacy file for the app itself and does not check the app's bundles. I had hoped that the problem was just that we were using `.copy()` instead of `.process()` for the xcprivacy file, but changing that had no effect.

Might need to file a DTS because things seem pretty straightforwardly broken on Apple's end and their sample code doesn't actually work.

**Comment by tgoyne** [comment]
https://github.com/apple/swift-package-manager/issues/7317 and https://github.com/firebase/firebase-ios-sdk/issues/12557 also report that privacy manifests in static frameworks just plain don't work at the moment. If this isn't fixed by May 1 we can work around it by forcing RealmSwift to be built as a dynamic framework, but that'll increase app binary sizes and startup times.

**Comment by tgoyne** [comment]
#8561 makes it so that you can build RealmSwift as a dynamic framework when installing via SPM by selecting "Embed & Sign" in the Frameworks, Libraries, and Embedded Content section, and afaict this results in app store connect actually using our privacy manifest. Alternatively, if you wish to continue statically linking RealmSwift you can manually add our privacy manifest declarations to your app's privacy manifest. There doesn't appear to be any other options with SPM.
