### ISSUE TITLE
Support Swift enums

### ISSUE THREAD

**Issue by aschuch** [realm/realm-swift#921]
Swift adds great new features to enums.

However, it is not possible to directly persist enums to a Realm, because of the libraries use of the `dynamic` keyword (Obj-C only).
At the moment I am solving such issues like the following, but this should really be handled by the RLMObject behind the scenes.

Open for other suggestions ✨

``` swift
enum State: String {
    case Open = "open"
    case Closed = "closed"
}

class Foo: RLMObject {
    dynamic var stateRaw = ""
    var state: State {
        get {
            if let a = State.fromRaw(stateRaw) {
                return a
            }
            return .Closed
        }
    }
}
```

**Comment by gabro** [comment]
This would be really nice to have, especially when dealing with JSON data.

In the meanwhile the snippet by @aschuch (thank you!) can be a little shorter using `??`:

```
var state: State {
  get {
    return State(rawValue: stateRaw) ?? .Closed
  }
}
```

**Comment by danyalaytekin** [comment]
Is this still the case now that we have RealmSwift?

**Comment by segiddins** [comment]
@danyalaytekin unfortunately, this is still the case, as Realm Swift still relies on properties being `dynamic`.

**Comment by danyalaytekin** [comment]
@segiddins np, thanks for the super-quick confirmation! :+1:

**Comment by frazer-rbsn** [comment]
Would love to see this implemented! Thanks guys!

**Comment by segiddins** [comment]
@frazer-rbsn this is still impossible, even as of Swift 2.0, as the runtime doesn't give us the information we need to be able to determine what we need to store under the hood.

**Comment by frazer-rbsn** [comment]
@segiddins 
Thanks for looking into this. The workaround posted here is simple and works a treat anyway. Thanks!

**Comment by tom-sparo** [comment]
For anyone who comes across this in the future -- KVC is a little bit trickier with using the raws if you don't want external users to have to worry about remembering which fields are backed by raws.  So I've found a good way is to override the `setValue(:value :undefinedKey)` and `valueForUndefinedKey` methods to make these computed properties KVC compliant.

**Comment by marchy** [comment]
Any progress/updates on this guys? This is really a core use case for domain modeling, would be super useful to have this supported first-hand (or at least a section about the current best-practice workaround in the docs). Pretty please.

**Comment by marchy** [comment]
@segiddins In terms of runtime not giving you enough info, what do you mean by this? Could you not implement a simple protocol that users would have to have their enums implement to give you whatever it is that's needed (ie: CustomStringConvertible for example, if you need to map the enum to a string to persist). Or your own RealmEnumValueConvertible in case already implement CustomStringConvertible and want to differ the persisted value from it (rare, but could be a valid scenario).

PS: I find the deltas between the model objects and what's needed to persist them in Realm is blowing up our domain - I think it would be a great goal for the team to try to prioritize minimizing these differences. I think enum persistence would be a great win on this front.

**Comment by piv199** [comment]
Is there any changes as for Swift 3.0?

**Comment by jpsim** [comment]
Yes, lots. But none regarding Swift enums and Realm.

**Comment by marchy** [comment]
@jpsim I think what @piv199 meant was whether Swift 3.0 added any of the runtime info that @segiddins  mentioned eg: "...as of Swift 2.0, as the runtime doesn't give us the information we need to be able to determine what we need to store under the hood".

Also, what do you guys think of my proposed solution to provide a protocol that enums can adopt in order to provide you with the serialized info you need?

**Comment by jpsim** [comment]
Yes, I understood that, but should have been clearer in my response. There are no changes in Swift 3 that would allow us to do this.

> Also, what do you guys think of my proposed solution to provide a protocol that enums can adopt in order to provide you with the serialized info you need?

This would have to be done more comprehensively, allowing the decomposition of all types into Realm primitives in order to keep Realm files cross-platform, but yes this is something that should be done.

**Comment by HT154** [comment]
It's possible to declare scalar-type-backed enums as @objc. Properties with declared @objc enum types can de marked dynamic, so wouldn't this enable realm to access the values? I've used this approach with Core Data in the past:
```swift
import CoreData
class Thread: NSManagedObject {
    @NSManahed var state: State
    @objc enum State: Int64 {
        case ready
        case running
        case waiting
    }
}
```

**Comment by AbelToy** [comment]
Would native enums be easier to support with the [changes introduced in Swift 4.2](https://github.com/apple/swift-evolution/blob/master/proposals/0194-derived-collection-of-enum-cases.md), or is there anything else required?

**Comment by bjarkehs** [comment]
It was mention in #2375 that work is being done on supporting types that implement `RawRepresentable`. I understand that `RawRepresentable` types cannot be used as properties, and thus you would still need to do the juggling with a raw value and then a computed property.

Recently I've started using the [Tagged](https://github.com/pointfreeco/swift-tagged) library. So I do something along the lines of:

```swift
final class Todo: Object {
    enum TodoIdTag {}
    typealias Identifier = Tagged<TodoIdTag, String>

    @objc dynamic var rawId: Identifier.RawValue = UUID().uuidString
    
    var id: Identifier {
        get {
            return Identifier(rawValue: self.rawId)
        }
        set {
            self.rawId = newValue.rawValue
        }
    }
}
```

However this gets really confusing when finding a single object using `object(ofType:forPrimaryKey:)`, since I'd like to use the computed id property. `Tagged` extends `RawRepresentable` so I can just use `id.rawValue`, but if I forget my app crashes in a fiery ball of death.

It would be great if `func dynamicBridgeCast<T>(fromSwift x: T) -> Any` could allow `RawRepresentable` types. Basically this could be done by checking if it's a `RawRepresentable` type and then instead of passing the `RawRepresentable` type just pass the `rawValue`.

Maybe something like:
```swift
extension RawRepresentable: CustomObjectiveCBridgeable where RawValue: CustomObjectiveCBridgeable {
    static func bridging(objCValue: Any) -> Int64 {
        return objCValue as! RawValue
    }
    var objCValue: Any {
        return self.rawValue
    }
}
```

**Comment by tgoyne** [comment]
The big limiting factor is that the property getter/setters which actually read from and write to the Realm file are implemented via the objective-c runtime, which means that they have to be types which obj-c supports. RealmOptional and List circumvent this by doing fairly complicated things that unfortunately involve a hardcoded list of the supported types on the obj-c side, so it wouldn't be totally straightforward to generalize it to a type which lets you pick a storage type, a mapped type, and a conversion function.

[SE-0258](https://github.com/apple/swift-evolution/blob/master/proposals/0258-property-delegates.md) probably will make it possible to at least make the wrapper property approach a lot simpler and work better, but as always the fact that it doesn't really interop with obj-c may limit how good the end result can be.
